---

- pause:
    prompt: "Do you want to execute DELETE of VM: {{ outer_item.key }} with FLAGS:{{ outer_item.value.flags }} (yes/no)?"
  register: vm_delete_question
  tags: vm_delete

- block:
  - import_tasks: stop_vms.yml

  - name: "Delete VM {{ outer_item.key }}"
    command: virsh undefine {{ outer_item.key }}
    register: vm_delete_output
    when:
      - "'force' not in outer_item.value.flags"

  - name: "Force delete VM {{ outer_item.key }}"
    command: virsh undefine {{ outer_item.key }} --remove-all-storage
    register: vm_delete_output_force
    when:
      - "'force' in outer_item.value.flags"

  - block:
    - pause:
        prompt: "{{vm_delete_output.stdout_lines}}. Press ENTER to continue"
    when: "'force' not in outer_item.value.flags"

  - block:
    - pause:
        prompt: "{{vm_delete_output_force.stdout_lines}}. Press ENTER to continue"
    when: "'force' in outer_item.value.flags"

      
  when: 
    - vm_delete_question.user_input=="yes"
    - outer_item.key in all_vms.list_vms
  tags: vm_delete   
