---
# tasks file for initial_setup

- name: Show info about the env this host belongs to
  become: true
  debug:
    msg: "This host is in {{ env }} environment!!!"

- include: base_python.yml
- include: users.yml
