---
- name: Pull docker image for nginx and run container with it
  hosts: docker-hosts
  gather_facts: false

  tasks:    
    - name: Start container with nginx image
      docker_container: 
        name: nginx
        image: nginx:mainline-alpine
        published_ports: 
          - '{{ redmine_port }}:{{ redmine_port }}'
          - '{{ gitlab_port }}:{{ gitlab_port }}'
        volumes: 
          - "{{ docker_data }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
          - "{{ docker_data }}/nginx/conf.d:/etc/nginx/conf.d:ro"
          - "{{ docker_data }}/nginx/ssl:/root/ssl:ro"
          - "{{ docker_data }}/nginx/logs:/var/log/nginx"
        networks: 
          - name: web_internal
        restart_policy: always
      become: true
